(load "package://hrpsys_ros_bridge_tutorials/euslisp/hironxjsk-interface.l")
(hironxjsk-init)
(objects (list *hironxjsk*))
;;(send *ri* :angle-vector (send *hironxjsk* :reset-manip-pose))
(send *hironxjsk* :head :look-at
      (send (send (send *hironxjsk* :torso :end-coords :copy-worldcoords)
                  :translate #f(750 0 0)) :worldpos))
(send *irtviewer* :draw-objects)  ;; Only for display
(send *ri* :angle-vector (send *hironxjsk* :angle-vector) 1000)
(send *ri* :wait-interpolation)
